loki:
  enabled: true
  persistence:
    enabled: false
    accessMode:
    - ReadWriteOnce:
    size: 1Gi

promtail:
  enabled: false
  config:
    logLevel: info
    serverPort: 3101
    clients:
    - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

fluent-bit:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: latest
