name: Deploy Loki to aws

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "loki/**"

jobs:
  deploy-loki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0' # default is latest stable
        id: install
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0  # Adjust to the latest stable version

      - name: Update kube config
        run: aws eks update-kubeconfig --name primuslearning

      - name: Deploy Loki with Helm
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm uninstall atlantis --namespace loki --ignore-not-found
          sleep 60s
          helm upgrade --install loki grafana/loki-stack \
            --namespace loki --create-namespace \
            --values loki-values-pomtail.yaml
